---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: diskencrypt=false release=prod ubuntuversion=jammy arch=amd64 username=cbcadmin password=ohZa8Ien 
