---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: diskencrypt=false release=prod ubuntuversion=focal arch=amd64 username=base password=Rocks123 epassword=\$6\$RsDAmpXBiF8Ev5ub\$BCEVoMK/MKdUQpJEykScLOgx9S8jw4TZCQyKutCfDQ06Dbk24E1u//ofUWFl39zRTyU8Ex45k634JjNDqCTJh.
